### ISSUE TITLE
Bad credentials

### ISSUE THREAD

**Issue by acron0** [DeLaGuardo/clojure-lint-action#4]
Using the following yaml:
```yaml
steps:
    - uses: actions/checkout@v1
    - uses: DeLaGuardo/clojure-lint-action@v1
      with:
        clj-kondo-args: --lint src
```

Fails with:

```
/usr/bin/docker run --name e87b52800af7d2186d48a18d08b69dd6efd1d6_8b8cd5 --label e87b52 --workdir /github/workspace --rm -e INPUT_CLJ-KONDO-ARGS -e INPUT_GITHUB_TOKEN -e HOME -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/works-hub/works-hub":"/github/workspace" e87b52:800af7d2186d48a18d08b69dd6efd1d6  "--lint src"
Error Error: Received status code 401
    at IncomingMessage.res.on (/action/lib/request.js:13:39)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
{"message":"Bad credentials","documentation_url":"https://developer.github.com/v3"}
```

I tried adding Github Token (Personal access token?) and it complained that it needed to be authed using GitHub App.

**Comment by acron0** [comment]
PEBKAC
